# Generated by Django 5.2.6 on 2025-09-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workshop_workshopregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopregistration',
            name='payment_proof_url',
        ),
        migrations.AddField(
            model_name='workshop',
            name='account_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workshop',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workshop',
            name='bank_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='workshop',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/qr/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='workshop',
            name='upi_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/proofs/'),
        ),
    ]
