# Generated by Django 5.2.6 on 2025-09-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_workshopregistration_payment_proof_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Payment Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
