# Generated by Django 5.2.6 on 2025-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workshopregistration_admin_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='image_url',
        ),
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/images/'),
        ),
    ]
